# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='comics')),
                ('synopsis', models.TextField()),
                ('slug', models.SlugField(max_length=250)),
                ('price', models.FloatField()),
                ('start_date', models.DateField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='categoryC', to='tiendita.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='companies')),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='superheroes')),
                ('history', models.TextField()),
                ('number', models.IntegerField()),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='superhero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superheroC', to='tiendita.SuperHero'),
        ),
    ]
