# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0002_superhero_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyC', to='tiendita.Company'),
        ),
    ]
